server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc
    username: root
    password: "sally@0405"
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

jwt:
  token:
    secretKey: umceightfightingjwttokenauthentication
    expiration:
      access: 14400000

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: umc-5th
      review-path: review
    stack:
      auto: false